unstable_features = true

required_version = "1.4.22"
edition = "2018"

format_code_in_doc_comments = true
match_block_trailing_comma = true
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
